/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://eqvrirhqu5hhzdltmsd3k4fs6e.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oh63hvfht5g2xl3lfvuijdtere",
    "aws_cognito_identity_pool_id": "us-west-1:2df6f85c-62f0-42d1-8747-d951ab604b0d",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_HID43kQnN",
    "aws_user_pools_web_client_id": "4p3tr0m006ergk1v13ev6rh6qk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
